name: "\U0001F680 Pull Request"
description: Pull Request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this form!
  - type: textarea
    id: pr-description
    attributes:
      label: Clear and concise description of the problem
      description: PR description
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/.github/contributing.md).
          required: true
        - label: Read the [docs](https://vitejs.dev/guide).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
